export const electData = [
  {
    img: "/uploads/seed/ElectServiceImages/fan-ser-img1.png",
    title: "Cieling fan",
    description:
      "Installation of new ceiling fan including wiring and mounting.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Fan Service",
    isPopular: true,
  },
  {
    img: "/uploads/seed/ElectServiceImages/fan-ser-img2.png",
    title: "Fancy Cieling fan",
    description:
      "Stylish and decorative ceiling fan installation and repair service.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Fan Service",
  },
  {
    img: "/uploads/seed/ElectServiceImages/fan-ser-img3.png",
    title: "Wall mountend fan",
    description:
      "Professional installation and repair service for wall-mounted fans.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Fan Service",
  },
  {
    img: "/uploads/seed/ElectServiceImages/fan-ser-img4.png",
    title: "Exhaust fan",
    description:
      "Efficient exhaust fan installation and repair for better air ventilation.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Fan Service",
  },
  {
    img: "/uploads/seed/ElectServiceImages/fan-ser-img5.png",
    title: "Cabin ceiling fan",
    description: "Compact ceiling fan installation and maintenance.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Fan Service",
  },
  {
    img: "/uploads/seed/ElectServiceImages/quickCheckElectImg.png",
    title: "QuickCheck",
    description:
      "Fast inspection service to identify electrical issues quickly.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Fan Service",
  },
  {
    img: "/uploads/seed/ElectServiceImages/light-ser-img1.png",
    title: "Ceiling panel light",
    description:
      "Installation and repair service for modern LED ceiling panel lights.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Light Service",
  },
  {
    img: "/uploads/seed/ElectServiceImages/light-ser-img2.png",
    title: "LED strip light",
    description:
      "Installation and setup of decorative LED strip lighting for homes and offices.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Light Service",
    isPopular: true,
  },
  {
    img: "/uploads/seed/ElectServiceImages/light-ser-img3.png",
    title: "Profile light",
    description:
      "Sleek profile light installation and repair for modern interior lighting.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Light Service",
  },
  {
    img: "/uploads/seed/ElectServiceImages/light-ser-img4.png",
    title: "Track light",
    description:
      "Adjustable track lighting installation to highlight and enhance your home or workspace.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Light Service",
  },
  {
    img: "/uploads/seed/ElectServiceImages/light-ser-img5.png",
    title: "Spotlight",
    description:
      "Focused spotlight setup to brighten specific areas with stylish and precise lighting.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Light Service",
  },
  {
    img: "/uploads/seed/ElectServiceImages/light-ser-img6.png",
    title: "Mirror light",
    description:
      "Elegant mirror lighting installation for clear visibility and a perfect grooming experience.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Light Service",
  },
  {
    img: "/uploads/seed/ElectServiceImages/light-ser-img7.png",
    title: "Outdoor light",
    description:
      "Durable outdoor lighting solutions to brighten and secure exterior spaces.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Light Service",
  },
  {
    img: "/uploads/seed/ElectServiceImages/quickCheckElectImg.png",
    title: "QuickCheck",
    description:
      "Fast inspection service to identify electrical issues quickly.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Light Service",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sb-ser-img1.png",
    title: "Complete switch board",
    description:
      "Full switchboard installation and repair for safe and organized electrical control.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Switch board",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sb-ser-img2.png",
    title: "One switch",
    description:
      "Quick installation or replacement of a single electrical switch with safety and precision.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Switch board",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sb-ser-img3.png",
    title: "One switch socket",
    description:
      "Installation and setup of a single switch socket for safe and convenient electrical access.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Switch board",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sb-ser-img4.png",
    title: "Fan regulator",
    description:
      "Installation and setup of a fan regulator for smooth speed control.",
    rating: 3.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Switch board",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sb-ser-img5.png",
    title: "Dimmer switch",
    description:
      "Smart dimmer switch installation to adjust lighting brightness as per your mood.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Switch board",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sb-ser-img6.png",
    title: "MCB change in Board",
    description:
      "Safe replacement of MCB for better protection and smooth electrical performance.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Switch board",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sb-ser-img7.png",
    title: "Smart switch",
    description:
      "Advanced smart switch installation for convenient and app-controlled lighting.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Switch board",
  },
  {
    img: "/uploads/seed/ElectServiceImages/quickCheckElectImg.png",
    title: "QuickCheck",
    description:
      "Fast inspection service to identify electrical issues quickly.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Switch board",
  },
  {
    img: "/uploads/seed/ElectServiceImages/wir-ser-img1.png",
    title: "Short circuit wiring",
    description:
      "Quick detection and repair of short circuit issues to restore electrical safety.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Wiring",
    isPopular: true,
  },
  {
    img: "/uploads/seed/ElectServiceImages/wir-ser-img2.png",
    title: "Switch board wiring",
    description:
      "Neat and reliable wiring setup for properly functioning switchboards.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Wiring",
  },
  {
    img: "/uploads/seed/ElectServiceImages/wir-ser-img3.png",
    title: "Concealed wiring",
    description:
      "Hidden and safe electrical wiring installation for a clean and modern interior look.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Wiring",
  },
  {
    img: "/uploads/seed/ElectServiceImages/wir-ser-img4.png",
    title: "Open wiring",
    description:
      "Secure and organized surface wiring solutions for easy maintenance and quick setup.",
    rating: 3.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Wiring",
  },
  {
    img: "/uploads/seed/ElectServiceImages/wir-ser-img5.png",
    title: "Pipe wiring",
    description:
      "Protective pipe wiring installation for safe and long-lasting electrical connections.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Wiring",
  },
  {
    img: "/uploads/seed/ElectServiceImages/wir-ser-img6.png",
    title: "Clip wiring",
    description:
      "Simple and economical wiring installation using clips for quick and tidy electrical setup.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Wiring",
  },
  {
    img: "/uploads/seed/ElectServiceImages/wir-ser-img7.png",
    title: "Casing-patti wiring",
    description:
      "Neat casing-patti wiring solution to keep electrical cables safe and well-organized.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Wiring",
  },
  {
    img: "/uploads/seed/ElectServiceImages/quickCheckElectImg.png",
    title: "QuickCheck",
    description:
      "Fast inspection service to identify electrical issues quickly.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Wiring",
  },
  {
    img: "/uploads/seed/ElectServiceImages/hl-ser-img1.png",
    title: "Pendant light",
    description:
      "Stylish pendant light installation to add elegance and focused illumination to your space.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Hanging light",
  },
  {
    img: "/uploads/seed/ElectServiceImages/hl-ser-img2.png",
    title: "Cluster pendant light",
    description:
      "Installation of multi-pendant lighting to create a beautiful and decorative lighting centerpiece.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Hanging light",
  },
  {
    img: "/uploads/seed/ElectServiceImages/hl-ser-img3.png",
    title: "Liner hanging light",
    description:
      "Sleek linear hanging light installation for modern and evenly distributed lighting.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Hanging light",
  },
  {
    img: "/uploads/seed/ElectServiceImages/hl-ser-img4.png",
    title: "Drum pendant light",
    description:
      "Elegant drum-style pendant light installation for soft and stylish ambient lighting.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Hanging light",
  },
  {
    img: "/uploads/seed/ElectServiceImages/hl-ser-img5.png",
    title: "Glass hanging light",
    description:
      "Premium glass hanging light installation for a classy and elegant lighting look.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Hanging light",
  },
  {
    img: "/uploads/seed/ElectServiceImages/hl-ser-img6.png",
    title: "Cage hanging light",
    description:
      "Trendy cage-style hanging light installation for a modern and artistic ambiance.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Hanging light",
  },
  {
    img: "/uploads/seed/ElectServiceImages/hl-ser-img7.png",
    title: "Industrial hanging light",
    description:
      "Rugged industrial-style hanging light installation for a bold and vintage-inspired look.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Hanging light",
  },
  {
    img: "/uploads/seed/ElectServiceImages/hl-ser-img8.png",
    title: "Wooden hanging light",
    description:
      "Natural wooden hanging light installation to bring warmth and aesthetic charm to interiors.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Hanging light",
  },
  {
    img: "/uploads/seed/ElectServiceImages/quickCheckElectImg.png",
    title: "QuickCheck",
    description:
      "Fast inspection service to identify electrical issues quickly.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Hanging light",
  },
  {
    img: "/uploads/seed/ElectServiceImages/wl-ser-img1.png",
    title: "Sconce wall light",
    description:
      "Elegant wall sconce installation to enhance decor with soft and stylish lighting.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Wall light",
  },
  {
    img: "/uploads/seed/ElectServiceImages/wl-ser-img2.png",
    title: "Up & Down wall light",
    description:
      "Modern wall light installation that illuminates both upward and downward for a stylish glow.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Wall light",
    isPopular: true,
  },
  {
    img: "/uploads/seed/ElectServiceImages/wl-ser-img3.png",
    title: "Picture wall light",
    description:
      "Focused wall light installation to highlight paintings, photos, and artwork beautifully.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Wall light",
  },
  {
    img: "/uploads/seed/ElectServiceImages/wl-ser-img4.png",
    title: "Bedside wall light",
    description:
      "Soft and convenient wall lighting setup designed for easy nighttime use and comfort.",
    rating: 3.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Wall light",
  },
  {
    img: "/uploads/seed/ElectServiceImages/wl-ser-img5.png",
    title: "LED wall panel light",
    description:
      "Sleek LED wall panel installation for bright, energy-efficient, and modern lighting.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Wall light",
  },
  {
    img: "/uploads/seed/ElectServiceImages/wl-ser-img6.png",
    title: "Crystal wall light",
    description:
      "crystal wall light installation to add sparkle and elegance to your interiors.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Wall light",
  },
  {
    img: "/uploads/seed/ElectServiceImages/wl-ser-img7.png",
    title: "Swing arm wall light",
    description:
      "Adjustable swing arm wall light installation for flexible and convenient focused lighting.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Wall light",
  },
  {
    img: "/uploads/seed/ElectServiceImages/wl-ser-img8.png",
    title: "Outdoor wall light",
    description:
      "Weather-resistant outdoor wall light installation for better visibility and exterior safety.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Wall light",
  },
  {
    img: "/uploads/seed/ElectServiceImages/quickCheckElectImg.png",
    title: "QuickCheck",
    description:
      "Fast inspection service to identify electrical issues quickly.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Wall light",
  },
  {
    img: "/uploads/seed/ElectServiceImages/cd-ser-img1.png",
    title: "Crystal chandelier",
    description:
      "Elegant crystal chandelier installation to add luxury and dazzling beauty to your space.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Chandelier",
    isPopular: true,
  },
  {
    img: "/uploads/seed/ElectServiceImages/cd-ser-img2.png",
    title: "Modern chandelier",
    description:
      "Stylish modern chandelier installation to give your space a sleek and contemporary look.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Chandelier",
  },
  {
    img: "/uploads/seed/ElectServiceImages/cd-ser-img3.png",
    title: "Candle chandelier",
    description:
      "Classic candle-style chandelier installation for a timeless and royal lighting ambiance.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Chandelier",
  },
  {
    img: "/uploads/seed/ElectServiceImages/cd-ser-img4.png",
    title: "Sputnik chandelier",
    description:
      "Trendy sputnik chandelier installation for a bold, artistic, and modern lighting statement.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Chandelier",
  },
  {
    img: "/uploads/seed/ElectServiceImages/cd-ser-img5.png",
    title: "Drum chandelier",
    description:
      "Stylish drum-shaped chandelier installation for soft, elegant, and balanced lighting.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Chandelier",
  },
  {
    img: "/uploads/seed/ElectServiceImages/cd-ser-img6.png",
    title: "Glass chandelier",
    description:
      "Premium glass chandelier installation to create a bright and sophisticated lighting effect.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Chandelier",
  },
  {
    img: "/uploads/seed/ElectServiceImages/cd-ser-img7.png",
    title: "Wooden chandelier",
    description:
      "Artistic wooden chandelier installation to bring natural charm and warmth to your décor.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Chandelier",
  },
  {
    img: "/uploads/seed/ElectServiceImages/cd-ser-img8.png",
    title: "Mini chandelier",
    description:
      "Compact and stylish chandelier installation for subtle elegance in small spaces.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Chandelier",
  },
  {
    img: "/uploads/seed/ElectServiceImages/cd-ser-img9.png",
    title: "Tiered chandelier",
    description:
      "Multi-level tiered chandelier installation for a grand and luxurious lighting centerpiece.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Chandelier",
  },
  {
    img: "/uploads/seed/ElectServiceImages/cd-ser-img10.png",
    title: "Pendant chandelier",
    description:
      "Modern pendant-style chandelier installation for focused lighting with a stylish flair.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Chandelier",
  },
  {
    img: "/uploads/seed/ElectServiceImages/quickCheckElectImg.png",
    title: "QuickCheck",
    description:
      "Fast inspection service to identify electrical issues quickly.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Chandelier",
  },
  {
    img: "/uploads/seed/ElectServiceImages/MCB-ser-img1.png",
    title: "Single phase MCB",
    description:
      "Reliable single-phase MCB installation for efficient protection of your home’s electrical circuit.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "MCB & Submeter",
  },
  {
    img: "/uploads/seed/ElectServiceImages/MCB-ser-img2.png",
    title: "Double phase MCB",
    description:
      "Safe and efficient double-phase MCB installation for balanced electrical circuit protection.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "MCB & Submeter",
    isPopular: true,
  },
  {
    img: "/uploads/seed/ElectServiceImages/MCB-ser-img3.png",
    title: "Three phase MCB",
    description:
      "Robust three-phase MCB installation to safeguard high-power electrical systems efficiently.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "MCB & Submeter",
  },
  {
    img: "/uploads/seed/ElectServiceImages/MCB-ser-img4.png",
    title: "TPN MCB",
    description:
      "Reliable TPN (Triple Pole & Neutral) MCB installation for complete protection of industrial and heavy-duty circuits.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "MCB & Submeter",
  },
  {
    img: "/uploads/seed/ElectServiceImages/MCB-ser-img5.png",
    title: "Complete MCB box",
    description:
      "Full MCB box installation for organized and secure electrical circuit management.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "MCB & Submeter",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sb-ser-img1.png",
    title: "Single phase ELCB/RCCB",
    description:
      "Safe single-phase ELCB/RCCB installation to protect against electric shocks and leakage currents.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "MCB & Submeter",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sb-ser-img2.png",
    title: "Three phase ELCB/RCCB",
    description:
      "Reliable three-phase ELCB/RCCB installation for complete protection against electrical faults and leakage.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "MCB & Submeter",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sb-ser-img3.png",
    title: "Single phase sub meter",
    description:
      "Accurate single-phase sub-meter installation for precise electricity usage monitoring.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "MCB & Submeter",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sb-ser-img4.png",
    title: "Three phase sub meter",
    description:
      "Reliable three-phase sub-meter installation for precise monitoring of high-power electricity usage.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "MCB & Submeter",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sb-ser-img5.png",
    title: "Sub meter wiring setup",
    description:
      "Professional wiring setup for sub-meters to ensure accurate and safe electricity measurement.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "MCB & Submeter",
  },
  {
    img: "/uploads/seed/ElectServiceImages/quickCheckElectImg.png",
    title: "QuickCheck",
    description:
      "Fast inspection service to identify electrical issues quickly.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "MCB & Submeter",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sensor-ser-img1.png",
    title: "Smart switch automation",
    description:
      "Advanced smart switch setup for automated and app-controlled lighting convenience.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Sensor & Automation",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sensor-ser-img2.png",
    title: "Day/Night sensor light",
    description:
      "Intelligent sensor light installation that automatically turns on at night and off during the day.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Sensor & Automation",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sensor-ser-img3.png",
    title: "Touch switch panel",
    description:
      "Modern touch switch panel installation for sleek, convenient, and tech-savvy control of lights.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Sensor & Automation",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sensor-ser-img4.png",
    title: "Voice control setup",
    description:
      "Hands-free voice-controlled system installation to manage lights and appliances effortlessly.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Sensor & Automation",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sensor-ser-img5.png",
    title: "PIR motion sensor",
    description:
      "Smart motion sensor installation that detects movement to automatically control lighting and security.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Sensor & Automation",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sensor-ser-img6.png",
    title: "Water over flow alarm",
    description:
      "Reliable water overflow alarm installation to prevent spillage and protect your home from water damage.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Sensor & Automation",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sensor-ser-img7.png",
    title: "Fully water automation sensor",
    description:
      "Advanced water automation sensor setup for smart, automated control of water systems and leak prevention.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Sensor & Automation",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sensor-ser-img8.png",
    title: "Home automation setup",
    description:
      "Complete home automation installation for smart control of lights, appliances, and security systems.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Sensor & Automation",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sensor-ser-img9.png",
    title: "Motion sensor",
    description:
      "Intelligent motion sensor installation to detect movement and automate lighting or security systems.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Sensor & Automation",
  },
  {
    img: "/uploads/seed/ElectServiceImages/sensor-ser-img10.png",
    title: "Occupancy sensor setup",
    description:
      "Smart occupancy sensor installation to automatically control lighting and save energy when rooms are unoccupied.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Sensor & Automation",
  },
  {
    img: "/uploads/seed/ElectServiceImages/quickCheckElectImg.png",
    title: "QuickCheck",
    description:
      "Fast inspection service to identify electrical issues quickly.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Sensor & Automation",
  },
];
