export const electData = [
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946405/ElectServiceImages/fan-ser-img1_fecqpn.png",
    title: "Cieling fan",
    description:
      "Installation of new ceiling fan including wiring and mounting.",
    rating: 5,
    duration: "30 mins",
    price: "199",
    button: "Add to cart",
    type: "Fan Service",
    isPopular: true,
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946329/ElectServiceImages/fan-ser-img2_izai1d.png",
    title: "Fancy Cieling fan",
    description:
      "Stylish and decorative ceiling fan installation and repair service.",
    rating: 4.5,
    duration: "30 mins",
    price: "349",
    button: "Add to cart",
    type: "Fan Service",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946329/ElectServiceImages/fan-ser-img3_ndfeoe.png",
    title: "Wall mountend fan",
    description:
      "Professional installation and repair service for wall-mounted fans.",
    rating: 4.5,
    duration: "30 mins",
    price: "199",
    button: "Add to cart",
    type: "Fan Service",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946329/ElectServiceImages/fan-ser-img4_agst2v.png",
    title: "Exhaust fan",
    description:
      "Efficient exhaust fan installation and repair for better air ventilation.",
    rating: 4,
    duration: "30 mins",
    price: "199",
    button: "Add to cart",
    type: "Fan Service",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946330/ElectServiceImages/fan-ser-img5_ykgqmc.png",
    title: "Cabin ceiling fan",
    description: "Compact ceiling fan installation and maintenance.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    button: "Add to cart",
    type: "Fan Service",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946329/ElectServiceImages/quickCheckElectImg_q05jgo.png",
    title: "QuickCheck",
    description:
      "Fast inspection service to identify electrical issues quickly.",
    rating: 5,
    duration: "30 mins",
    price: "299",
    button: "Add to cart",
    type: "Fan Service",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946408/ElectServiceImages/light-ser-img1_fem0to.png",
    title: "Ceiling panel light",
    description:
      "Installation and repair service for modern LED ceiling panel lights.",
    rating: 4.5,
    duration: "30 mins",
    price: "149",
    button: "Add to cart",
    type: "Light Service",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1775660399/ElectServiceImages/wl-ser-img8_p5axgp.png",
    title: "LED Tube light",
    description: "Installation LED tube lights.",
    rating: 4.5,
    duration: "30 mins",
    price: "149",
    button: "Add to cart",
    type: "Light Service",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946408/ElectServiceImages/light-ser-img2_mfu5zc.png",
    title: "LED roop light",
    description:
      "Installation and setup of decorative LED strip lighting for homes and offices.",
    rating: 4.5,
    duration: "30 mins",
    price: "49",
    button: "Add to cart",
    type: "Light Service",
    isPopular: true,
    priceType: "unit",
    unit: "per meter",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946408/ElectServiceImages/light-ser-img3_xqsmql.png",
    title: "Profile light",
    description:
      "Sleek profile light installation and repair for modern interior lighting.",
    rating: 4,
    duration: "30 mins",
    price: "99",
    button: "Add to cart",
    type: "Light Service",
    priceType: "unit",
    unit: "per meter",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946409/ElectServiceImages/light-ser-img4_ycnr2a.png",
    title: "Track light",
    description:
      "Adjustable track lighting installation to highlight and enhance your home or workspace.",
    rating: 4.5,
    duration: "30 mins",
    price: "349",
    button: "Add to cart",
    type: "Light Service",
    priceType: "unit",
    unit: "per meter",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946409/ElectServiceImages/light-ser-img5_kmqlmx.png",
    title: "Spotlight",
    description:
      "Focused spotlight setup to brighten specific areas with stylish and precise lighting.",
    rating: 4.5,
    duration: "30 mins",
    price: "149",
    button: "Add to cart",
    type: "Light Service",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946409/ElectServiceImages/light-ser-img6_djj0pd.png",
    title: "Mirror light",
    description:
      "Elegant mirror lighting installation for clear visibility and a perfect grooming experience.",
    rating: 4,
    duration: "30 mins",
    price: "149",
    button: "Add to cart",
    type: "Light Service",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946407/ElectServiceImages/hl-ser-img2_gvzq27.png",
    title: "Hanging light",
    description:
      "Installation of multi-pendant lighting to create a beautiful and decorative lighting centerpiece.",
    rating: 5,
    duration: "30 mins",
    button: "Add to cart",
    type: "Light Service",
    priceType: "range",
    priceRange: {
      min: 249,
      max: 699,
    },
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946416/ElectServiceImages/wl-ser-img1_bfdvyy.png",
    title: "Wall light",
    description:
      "Elegant wall sconce installation to enhance decor with soft and stylish lighting.",
    rating: 4,
    duration: "30 mins",
    button: "Add to cart",
    type: "Light Service",
    priceType: "range",
    priceRange: {
      min: 199,
      max: 499,
    },
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946404/ElectServiceImages/cd-ser-img1_wuubgi.png",
    title: "Chandelier",
    description:
      "Elegant crystal chandelier installation to add luxury and dazzling beauty to your space.",
    rating: 5,
    duration: "30 mins",
    button: "Add to cart",
    type: "Light Service",
    isPopular: true,
    priceType: "range",
    priceRange: {
      min: 499,
      max: 1999,
    },
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946329/ElectServiceImages/quickCheckElectImg_q05jgo.png",
    title: "QuickCheck",
    description:
      "Fast inspection service to identify electrical issues quickly.",
    rating: 5,
    duration: "30 mins",
    price: "299",
    button: "Add to cart",
    type: "Light Service",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946410/ElectServiceImages/sb-ser-img1_hexo12.png",
    title: "Complete switch board",
    description:
      "Full switchboard installation and repair for safe and organized electrical control.",
    rating: 4,
    duration: "30 mins",
    price: "349",
    button: "Add to cart",
    type: "Switch board",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946411/ElectServiceImages/sb-ser-img2_eoyphy.png",
    title: "One switch",
    description:
      "Quick installation or replacement of a single electrical switch with safety and precision.",
    rating: 4,
    duration: "30 mins",
    price: "99",
    button: "Add to cart",
    type: "Switch board",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946411/ElectServiceImages/sb-ser-img3_eryjpi.png",
    title: "One switch socket",
    description:
      "Installation and setup of a single switch socket for safe and convenient electrical access.",
    rating: 4,
    duration: "30 mins",
    price: "149",
    button: "Add to cart",
    type: "Switch board",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946411/ElectServiceImages/sb-ser-img4_axo6bm.png",
    title: "Fan regulator",
    description:
      "Installation and setup of a fan regulator for smooth speed control.",
    rating: 3.5,
    duration: "30 mins",
    price: "199",
    button: "Add to cart",
    type: "Switch board",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946411/ElectServiceImages/sb-ser-img5_c5zp5v.png",
    title: "Dimmer switch",
    description:
      "Smart dimmer switch installation to adjust lighting brightness as per your mood.",
    rating: 4,
    duration: "30 mins",
    price: "199",
    button: "Add to cart",
    type: "Switch board",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946411/ElectServiceImages/sb-ser-img6_nfxqfe.png",
    title: "MCB change in Board",
    description:
      "Safe replacement of MCB for better protection and smooth electrical performance.",
    rating: 4.5,
    duration: "30 mins",
    price: "299",
    button: "Add to cart",
    type: "Switch board",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946411/ElectServiceImages/sb-ser-img7_beokx8.png",
    title: "Smart switch",
    description:
      "Advanced smart switch installation for convenient and app-controlled lighting.",
    rating: 4.5,
    duration: "30 mins",
    price: "499",
    button: "Add to cart",
    type: "Switch board",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946329/ElectServiceImages/quickCheckElectImg_q05jgo.png",
    title: "QuickCheck",
    description:
      "Fast inspection service to identify electrical issues quickly.",
    rating: 5,
    duration: "30 mins",
    price: "299",
    button: "Add to cart",
    type: "Switch board",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946414/ElectServiceImages/wir-ser-img1_yczrro.png",
    title: "Short circuit wiring",
    description:
      "Quick detection and repair of short circuit issues to restore electrical safety.",
    rating: 4.5,
    duration: "30 mins",
    price: null,
    button: "Add to cart",
    type: "Wiring",
    isPopular: true,
    priceType: "inspection",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946415/ElectServiceImages/wir-ser-img3_mheyly.png",
    title: "Concealed wiring",
    description:
      "Hidden and safe electrical wiring installation for a clean and modern interior look.",
    rating: 4,
    duration: "30 mins",
    price: "299",
    button: "Add to cart",
    type: "Wiring",
    priceType: "unit",
    unit: "per point",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946415/ElectServiceImages/wir-ser-img5_ppije7.png",
    title: "Open wiring",
    description:
      "Protective pipe wiring installation for safe and long-lasting electrical connections.",
    rating: 4,
    duration: "30 mins",
    price: "199",
    button: "Add to cart",
    type: "Wiring",
    priceType: "unit",
    unit: "per point",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946415/ElectServiceImages/wir-ser-img6_y28uzg.png",
    title: "Clip wiring",
    description:
      "Simple and economical wiring installation using clips for quick and tidy electrical setup.",
    rating: 4,
    duration: "30 mins",
    price: "99",
    button: "Add to cart",
    type: "Wiring",
    priceType: "unit",
    unit: "per point",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946415/ElectServiceImages/wir-ser-img7_sbkps1.png",
    title: "Casing-patti wiring",
    description:
      "Neat casing-patti wiring solution to keep electrical cables safe and well-organized.",
    rating: 4,
    duration: "30 mins",
    price: "149",
    button: "Add to cart",
    type: "Wiring",
    priceType: "unit",
    unit: "per point",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946329/ElectServiceImages/quickCheckElectImg_q05jgo.png",
    title: "QuickCheck",
    description:
      "Fast inspection service to identify electrical issues quickly.",
    rating: 5,
    duration: "30 mins",
    price: "299",
    button: "Add to cart",
    type: "Wiring",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946409/ElectServiceImages/MCB-ser-img1_sshjpe.png",
    title: "Single phase MCB",
    description:
      "Reliable single-phase MCB installation for efficient protection of your home’s electrical circuit.",
    rating: 4,
    duration: "30 mins",
    price: "179",
    button: "Add to cart",
    type: "MCB & Submeter",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946410/ElectServiceImages/MCB-ser-img2_xltwzh.png",
    title: "Double pole MCB",
    description:
      "Safe and efficient double-phase MCB installation for balanced electrical circuit protection.",
    rating: 4,
    duration: "30 mins",
    price: "179",
    button: "Add to cart",
    type: "MCB & Submeter",
    isPopular: true,
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946410/ElectServiceImages/MCB-ser-img3_fxowna.png",
    title: "Three phase MCB",
    description:
      "Robust three-phase MCB installation to safeguard high-power electrical systems efficiently.",
    rating: 4,
    duration: "30 mins",
    price: "279",
    button: "Add to cart",
    type: "MCB & Submeter",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946410/ElectServiceImages/MCB-ser-img4_x40umo.png",
    title: "TPN MCB",
    description:
      "Reliable TPN (Triple Pole & Neutral) MCB installation for complete protection of industrial and heavy-duty circuits.",
    rating: 4.5,
    duration: "30 mins",
    price: "279",
    button: "Add to cart",
    type: "MCB & Submeter",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946410/ElectServiceImages/MCB-ser-img5_lnvgxl.png",
    title: "Complete MCB box",
    description:
      "Full MCB box installation for organized and secure electrical circuit management.",
    rating: 4.5,
    duration: "30 mins",
    price: null,
    button: "Add to cart",
    type: "MCB & Submeter",
    priceType: "inspection",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946413/ElectServiceImages/subm-ser-img1_uopaui.png",
    title: "Single phase ELCB/RCCB",
    description:
      "Safe single-phase ELCB/RCCB installation to protect against electric shocks and leakage currents.",
    rating: 4,
    duration: "30 mins",
    price: "299",
    button: "Add to cart",
    type: "MCB & Submeter",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946413/ElectServiceImages/subm-ser-img2_kcpiox.png",
    title: "Three phase ELCB/RCCB",
    description:
      "Reliable three-phase ELCB/RCCB installation for complete protection against electrical faults and leakage.",
    rating: 4,
    duration: "30 mins",
    price: "399",
    button: "Add to cart",
    type: "MCB & Submeter",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946414/ElectServiceImages/subm-ser-img3_svx48j.png",
    title: "Single phase sub meter",
    description:
      "Accurate single-phase sub-meter installation for precise electricity usage monitoring.",
    rating: 4,
    duration: "30 mins",
    price: "249",
    button: "Add to cart",
    type: "MCB & Submeter",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946414/ElectServiceImages/subm-ser-img4_t6zlpg.png",
    title: "Three phase sub meter",
    description:
      "Reliable three-phase sub-meter installation for precise monitoring of high-power electricity usage.",
    rating: 4,
    duration: "30 mins",
    price: "449",
    button: "Add to cart",
    type: "MCB & Submeter",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946329/ElectServiceImages/quickCheckElectImg_q05jgo.png",
    title: "QuickCheck",
    description:
      "Fast inspection service to identify electrical issues quickly.",
    rating: 5,
    duration: "30 mins",
    price: "299",
    button: "Add to cart",
    type: "MCB & Submeter",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946412/ElectServiceImages/sensor-ser-img1_zptew1.png",
    title: "Smart switch automation",
    description:
      "Advanced smart switch setup for automated and app-controlled lighting convenience.",
    rating: 4,
    duration: "30 mins",
    price: null,
    button: "Add to cart",
    type: "Sensor & Automation",
    priceType: "inspection",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946412/ElectServiceImages/sensor-ser-img2_enl3co.png",
    title: "Day/Night sensor light",
    description:
      "Intelligent sensor light installation that automatically turns on at night and off during the day.",
    rating: 4,
    duration: "30 mins",
    price: "349",
    button: "Add to cart",
    type: "Sensor & Automation",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946412/ElectServiceImages/sensor-ser-img3_az9fds.png",
    title: "Touch switch panel",
    description:
      "Modern touch switch panel installation for sleek, convenient, and tech-savvy control of lights.",
    rating: 4.5,
    duration: "30 mins",
    price: "599",
    button: "Add to cart",
    type: "Sensor & Automation",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946413/ElectServiceImages/sensor-ser-img6_epuowd.png",
    title: "Water over flow alarm",
    description:
      "Reliable water overflow alarm installation to prevent spillage and protect your home from water damage.",
    rating: 4.5,
    duration: "30 mins",
    price: "499",
    button: "Add to cart",
    type: "Sensor & Automation",
    priceType: "unit",
    unit: "per floor",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946413/ElectServiceImages/sensor-ser-img7_nluif4.png",
    title: "Fully water automation sensor",
    description:
      "Advanced water automation sensor setup for smart, automated control of water systems and leak prevention.",
    rating: 4,
    duration: "30 mins",
    price: "499",
    button: "Add to cart",
    type: "Sensor & Automation",
    priceType: "unit",
    unit: "per floor",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946413/ElectServiceImages/sensor-ser-img8_ma9aca.png",
    title: "Home automation setup",
    description:
      "Complete home automation installation for smart control of lights, appliances, and security systems.",
    duration: "30 mins",
    price: "Upcoming soon",
    type: "Sensor & Automation",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946413/ElectServiceImages/sensor-ser-img9_rvrw0y.png",
    title: "Motion sensor",
    description:
      "Intelligent motion sensor installation to detect movement and automate lighting or security systems.",
    rating: 4,
    duration: "30 mins",
    price: "349",
    button: "Add to cart",
    type: "Sensor & Automation",
    priceType: "fixed",
  },
  {
    img: "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774946329/ElectServiceImages/quickCheckElectImg_q05jgo.png",
    title: "QuickCheck",
    description:
      "Fast inspection service to identify electrical issues quickly.",
    rating: 5,
    duration: "30 mins",
    price: "299",
    button: "Add to cart",
    type: "Sensor & Automation",
    priceType: "fixed",
  },
];
