export const techData = [
  {
    img: "/uploads/seed/TechServiceImages/ac-ser-img1.png",
    title: "AC Installation",
    description:
      "Professional AC installation for efficient cooling and long-lasting performance.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: "/uploads/seed/TechServiceImages/ac-ser-img2.png",
    title: "AC Uninstallation",
    description: "Safe and hassle-free AC removal and uninstallation service.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: "/uploads/seed/TechServiceImages/ac-ser-img3.png",
    title: "Wiring Connection Setup",
    description:
      "Expert wiring and connection setup for smooth and reliable AC operation.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: "/uploads/seed/TechServiceImages/ac-ser-img4.png",
    title: "Cooling Problem Fixing",
    description: "Quick AC repair to restore optimal cooling and comfort.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
    isPopular: true,
  },
  {
    img: "/uploads/seed/TechServiceImages/ac-ser-img5.png",
    title: "Water Leakage Fixing",
    description:
      "Efficient solution for AC water leakage issues to prevent damage.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: "/uploads/seed/TechServiceImages/ac-ser-img6.png",
    title: "Noise Problem Fixing",
    description:
      "AC noise troubleshooting and repair for silent and smooth operation.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: "/uploads/seed/TechServiceImages/ac-ser-img7.png",
    title: "Gas Pressure Check/Gas Leakage Check",
    description:
      "Accurate gas inspection and leak detection for safe AC performance.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: "/uploads/seed/TechServiceImages/ac-ser-img8.png",
    title: "Gas Top Up",
    description:
      "Fast and reliable AC gas refill service to restore cooling efficiency.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: "/uploads/seed/TechServiceImages/ac-ser-img9.png",
    title: "Jet Pump Washing",
    description:
      "Thorough jet pump cleaning and maintenance for optimal water flow and performance.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: "/uploads/seed/TechServiceImages/quickCheckTechImg.png",
    title: "QuickCheck",
    description:
      "Fast inspection & instant solution for your appliances or electrical issues.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: "/uploads/seed/TechServiceImages/wm-ser-img1.png",
    title: "Machine not Work",
    description:
      "Quick troubleshooting and repair to get your washing machine running smoothly.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Washing Machine",
  },
  {
    img: "/uploads/seed/TechServiceImages/wm-ser-img2.png",
    title: "Noise/Vibration Issue",
    description:
      "Fixing noisy or vibrating machines for silent and stable operation.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Washing Machine",
  },
  {
    img: "/uploads/seed/TechServiceImages/wm-ser-img3.png",
    title: "Water not draining",
    description:
      "Efficient solution for water drainage problems to keep your machine flowing.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Washing Machine",
  },
  {
    img: "/uploads/seed/TechServiceImages/wm-ser-img4.png",
    title: "Spinning Problem",
    description:
      "Expert repair for washing machine spinning issues to ensure thorough washing.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "Washing Machine",
    isPopular: true,
  },
  {
    img: "/uploads/seed/TechServiceImages/wm-ser-img5.png",
    title: "Drain pipe fitting",
    description:
      "Proper drain pipe installation and fixing for hassle-free water outflow.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Washing Machine",
  },
  {
    img: "/uploads/seed/TechServiceImages/quickCheckTechImg.png",
    title: "QuickCheck",
    description:
      "Fast inspection & instant solution for your appliances or electrical issues.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    type: "Washing Machine",
  },
  {
    img: "/uploads/seed/TechServiceImages/refrigerator-ser-img1.png",
    title: "Cooling Issue",
    description:
      "Fast refrigerator repair to restore optimal cooling and freshness.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "Refrigerator",
  },
  {
    img: "/uploads/seed/TechServiceImages/refrigerator-ser-img2.png",
    title: "Water Leakage Issue",
    description:
      "Efficient solution for fridge water leakage to prevent mess and damage.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Refrigerator",
  },
  {
    img: "/uploads/seed/TechServiceImages/refrigerator-ser-img3.png",
    title: "Gas Refill",
    description:
      "Quick and safe fridge gas refill for proper cooling performance.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Refrigerator",
  },
  {
    img: "/uploads/seed/TechServiceImages/quickCheckTechImg.png",
    title: "QuickCheck",
    description:
      "Fast inspection & instant solution for your appliances or electrical issues.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    type: "Refrigerator",
  },
  {
    img: "/uploads/seed/TechServiceImages/ro-ser-img1.png",
    title: "New RO Installation",
    description:
      "Professional RO installation for pure and safe drinking water.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Water Purifier",
  },
  {
    img: "/uploads/seed/TechServiceImages/ro-ser-img2.png",
    title: "RO Uninstallation",
    description: "Safe and hassle-free RO uninstallation service.",
    rating: 3.5,
    duration: "30 mins",
    price: "120",
    type: "Water Purifier",
  },
  {
    img: "/uploads/seed/TechServiceImages/ro-ser-img3.png",
    title: "RO Filter Replacement",
    description:
      "Quick RO filter replacement to ensure clean and healthy water.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "Water Purifier",
  },
  {
    img: "/uploads/seed/TechServiceImages/ro-ser-img4.png",
    title: "Water not filtering",
    description:
      "Efficient troubleshooting for RO water flow and filtration issues.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Water Purifier",
    isPopular: true,
  },
  {
    img: "/uploads/seed/TechServiceImages/quickCheckTechImg.png",
    title: "QuickCheck",
    description:
      "Fast inspection & instant solution for your appliances or electrical issues.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    type: "Water Purifier",
  },
  {
    img: "/uploads/seed/TechServiceImages/geyser-ser-img1.png",
    title: "New Geyser Installation",
    description: "Professional geyser setup for reliable hot water supply.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "Geyser",
    isPopular: true,
  },
  {
    img: "/uploads/seed/TechServiceImages/geyser-ser-img2.png",
    title: "Geyser Uninstallation",
    description: "Safe and hassle-free geyser removal service.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Geyser",
  },
  {
    img: "/uploads/seed/TechServiceImages/geyser-ser-img3.png",
    title: "Geyser Not Heating",
    description: "Quick repair for geysers that fail to heat water properly.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Geyser",
  },
  {
    img: "/uploads/seed/TechServiceImages/geyser-ser-img4.png",
    title: "Geyser Leakage Issue",
    description: "Efficient solution to fix water leakage from geysers.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Geyser",
  },
  {
    img: "/uploads/seed/TechServiceImages/geyser-ser-img5.png",
    title: "Auto Cutoff Issue",
    description:
      "Expert repair for faulty geyser auto cutoff problems to ensure safety.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Geyser",
  },
  {
    img: "/uploads/seed/TechServiceImages/quickCheckTechImg.png",
    title: "QuickCheck",
    description:
      "Fast inspection & instant solution for your appliances or electrical issues.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    type: "Geyser",
  },
  {
    img: "/uploads/seed/TechServiceImages/oven-ser-img1.png",
    title: "Oven not Heating",
    description:
      "Fast repair to restore proper heating in your microwave oven.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Microwave Oven",
  },
  {
    img: "/uploads/seed/TechServiceImages/oven-ser-img2.png",
    title: "Buttons/Panel Not Working",
    description:
      "Expert fix for unresponsive microwave buttons or control panel.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "Microwave Oven",
  },
  {
    img: "/uploads/seed/TechServiceImages/oven-ser-img3.png",
    title: "Sparking Issue",
    description:
      "Safe repair for microwave sparking problems to prevent hazards.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Microwave Oven",
  },
  {
    img: "/uploads/seed/TechServiceImages/oven-ser-img4.png",
    title: "Electrical Connection Issue",
    description:
      "Reliable solution for microwave electrical connection faults.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Microwave Oven",
  },
  {
    img: "/uploads/seed/TechServiceImages/quickCheckTechImg.png",
    title: "QuickCheck",
    description:
      "Fast inspection & instant solution for your appliances or electrical issues.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    type: "Microwave Oven",
  },
  {
    img: "/uploads/seed/TechServiceImages/tv-ser-img1.png",
    title: "New TV Installation",
    description: "Professional TV setup for a perfect viewing experience.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "Television",
    isPopular: true,
  },
  {
    img: "/uploads/seed/TechServiceImages/tv-ser-img2.png",
    title: "TV Uninstallation",
    description: "Safe and hassle-free TV removal service.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
  {
    img: "/uploads/seed/TechServiceImages/tv-ser-img3.png",
    title: "Display Problem",
    description: "Quick repair for blurry, flickering, or faulty TV display.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
  {
    img: "/uploads/seed/TechServiceImages/tv-ser-img4.png",
    title: "Smart TV Remote Not Working",
    description: "Expert fix for unresponsive smart TV remotes.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
  {
    img: "/uploads/seed/TechServiceImages/tv-ser-img5.png",
    title: "Lines on Screen",
    description:
      "Efficient solution to remove lines or distortions from your screen.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "Television",
    isPopular: true,
  },
  {
    img: "/uploads/seed/TechServiceImages/tv-ser-img6.png",
    title: "Speaker or Sound Problem",
    description: "Clear and reliable sound repair for TV speakers",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
  {
    img: "/uploads/seed/TechServiceImages/tv-ser-img7.png",
    title: "LED TV Backlight Changing",
    description: "Fast backlight replacement for bright and even TV display.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
  {
    img: "/uploads/seed/TechServiceImages/tv-ser-img8.png",
    title: "Parts Replacement",
    description: "Genuine parts replacement to restore your TV’s performance.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
  {
    img: "/uploads/seed/TechServiceImages/tv-ser-img9.png",
    title: "TV Software Update",
    description: "Smart software updates to keep your TV running smoothly.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
  {
    img: "/uploads/seed/TechServiceImages/tv-ser-img10.png",
    title: "Connectivity Issue (WiFi/HDMI/USB)",
    description: "Reliable fix for WiFi, HDMI, or USB connectivity problems.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
  {
    img: "/uploads/seed/TechServiceImages/quickCheckTechImg.png",
    title: "QuickCheck",
    description:
      "Fast inspection & instant solution for your appliances or electrical issues.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
];
