const TECH_IMG_BASE =
  "https://res.cloudinary.com/dsr9kgkoj/image/upload/v1774947592/TechServiceImages/";

export const techData = [
  {
    img: TECH_IMG_BASE + "ac-ser-img1_vu6sku.png",
    title: "AC Installation",
    description:
      "Professional AC installation for efficient cooling and long-lasting performance.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: TECH_IMG_BASE + "ac-ser-img2_xr6m0i.png",
    title: "AC Uninstallation",
    description: "Safe and hassle-free AC removal and uninstallation service.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: TECH_IMG_BASE + "ac-ser-img3_i2kxmb.png",
    title: "Wiring Connection Setup",
    description:
      "Expert wiring and connection setup for smooth and reliable AC operation.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: TECH_IMG_BASE + "ac-ser-img4_kucsd4.png",
    title: "Cooling Problem Fixing",
    description: "Quick AC repair to restore optimal cooling and comfort.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
    isPopular: true,
  },
  {
    img: TECH_IMG_BASE + "ac-ser-img5_xu87r1.png",
    title: "Water Leakage Fixing",
    description:
      "Efficient solution for AC water leakage issues to prevent damage.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: TECH_IMG_BASE + "ac-ser-img6_stubiq.png",
    title: "Noise Problem Fixing",
    description:
      "AC noise troubleshooting and repair for silent and smooth operation.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: TECH_IMG_BASE + "ac-ser-img7_q8049d.png",
    title: "Gas Pressure Check/Gas Leakage Check",
    description:
      "Accurate gas inspection and leak detection for safe AC performance.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: TECH_IMG_BASE + "ac-ser-img8_tnqabj.png",
    title: "Gas Top Up",
    description:
      "Fast and reliable AC gas refill service to restore cooling efficiency.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: TECH_IMG_BASE + "ac-ser-img9_kqr5ww.png",
    title: "Jet Pump Washing",
    description:
      "Thorough jet pump cleaning and maintenance for optimal water flow and performance.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: TECH_IMG_BASE + "quickCheckTechImg_c1syfy.png",
    title: "QuickCheck",
    description:
      "Fast inspection & instant solution for your appliances or electrical issues.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    type: "AC Service",
  },
  {
    img: TECH_IMG_BASE + "wm-ser-img1_ncnjyz.png",
    title: "Machine not Work",
    description:
      "Quick troubleshooting and repair to get your washing machine running smoothly.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Washing Machine",
  },
  {
    img: TECH_IMG_BASE + "wm-ser-img2_c1rxjz.png",
    title: "Noise/Vibration Issue",
    description:
      "Fixing noisy or vibrating machines for silent and stable operation.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Washing Machine",
  },
  {
    img: TECH_IMG_BASE + "wm-ser-img3_y3nllv.png",
    title: "Water not draining",
    description:
      "Efficient solution for water drainage problems to keep your machine flowing.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Washing Machine",
  },
  {
    img: TECH_IMG_BASE + "wm-ser-img4_ugexo7.png",
    title: "Spinning Problem",
    description:
      "Expert repair for washing machine spinning issues to ensure thorough washing.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "Washing Machine",
    isPopular: true,
  },
  {
    img: TECH_IMG_BASE + "wm-ser-img5_a5asat.png",
    title: "Drain pipe fitting",
    description:
      "Proper drain pipe installation and fixing for hassle-free water outflow.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Washing Machine",
  },
  {
    img: TECH_IMG_BASE + "quickCheckTechImg_c1syfy.png",
    title: "QuickCheck",
    description:
      "Fast inspection & instant solution for your appliances or electrical issues.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    type: "Washing Machine",
  },
  {
    img: TECH_IMG_BASE + "refrigerator-ser-img1_sw3uni.png",
    title: "Cooling Issue",
    description:
      "Fast refrigerator repair to restore optimal cooling and freshness.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "Refrigerator",
  },
  {
    img: TECH_IMG_BASE + "refrigerator-ser-img2_wvfhv1.png",
    title: "Water Leakage Issue",
    description:
      "Efficient solution for fridge water leakage to prevent mess and damage.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Refrigerator",
  },
  {
    img: TECH_IMG_BASE + "refrigerator-ser-img3_o3kcmq.png",
    title: "Gas Refill",
    description:
      "Quick and safe fridge gas refill for proper cooling performance.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Refrigerator",
  },
  {
    img: TECH_IMG_BASE + "quickCheckTechImg_c1syfy.png",
    title: "QuickCheck",
    description:
      "Fast inspection & instant solution for your appliances or electrical issues.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    type: "Refrigerator",
  },
  {
    img: TECH_IMG_BASE + "ro-ser-img1_ydbue2.png",
    title: "New RO Installation",
    description:
      "Professional RO installation for pure and safe drinking water.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Water Purifier",
  },
  {
    img: TECH_IMG_BASE + "ro-ser-img2_klqsun.png",
    title: "RO Uninstallation",
    description: "Safe and hassle-free RO uninstallation service.",
    rating: 3.5,
    duration: "30 mins",
    price: "120",
    type: "Water Purifier",
  },
  {
    img: TECH_IMG_BASE + "ro-ser-img3_stoxrb.png",
    title: "RO Filter Replacement",
    description:
      "Quick RO filter replacement to ensure clean and healthy water.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "Water Purifier",
  },
  {
    img: TECH_IMG_BASE + "geyser-ser-img4_gquane.png",
    title: "Water not filtering",
    description:
      "Efficient troubleshooting for RO water flow and filtration issues.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Water Purifier",
    isPopular: true,
  },
  {
    img: TECH_IMG_BASE + "quickCheckTechImg_c1syfy.png",
    title: "QuickCheck",
    description:
      "Fast inspection & instant solution for your appliances or electrical issues.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    type: "Water Purifier",
  },
  {
    img: TECH_IMG_BASE + "geyser-ser-img1_jkzrml.png",
    title: "New Geyser Installation",
    description: "Professional geyser setup for reliable hot water supply.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "Geyser",
    isPopular: true,
  },
  {
    img: TECH_IMG_BASE + "geyser-ser-img2_doj9yy.png",
    title: "Geyser Uninstallation",
    description: "Safe and hassle-free geyser removal service.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Geyser",
  },
  {
    img: TECH_IMG_BASE + "geyser-ser-img3_bmrg6g.png",
    title: "Geyser Not Heating",
    description: "Quick repair for geysers that fail to heat water properly.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Geyser",
  },
  {
    img: TECH_IMG_BASE + "geyser-ser-img4_gquane.png",
    title: "Geyser Leakage Issue",
    description: "Efficient solution to fix water leakage from geysers.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Geyser",
  },
  {
    img: TECH_IMG_BASE + "geyser-ser-img5_mdypam.png",
    title: "Auto Cutoff Issue",
    description:
      "Expert repair for faulty geyser auto cutoff problems to ensure safety.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Geyser",
  },
  {
    img: TECH_IMG_BASE + "quickCheckTechImg_c1syfy.png",
    title: "QuickCheck",
    description:
      "Fast inspection & instant solution for your appliances or electrical issues.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    type: "Geyser",
  },
  {
    img: TECH_IMG_BASE + "oven-ser-img1_zw5zoa.png",
    title: "Oven not Heating",
    description:
      "Fast repair to restore proper heating in your microwave oven.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Microwave Oven",
  },
  {
    img: TECH_IMG_BASE + "oven-ser-img2_czqvpl.png",
    title: "Buttons/Panel Not Working",
    description:
      "Expert fix for unresponsive microwave buttons or control panel.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "Microwave Oven",
  },
  {
    img: TECH_IMG_BASE + "oven-ser-img3_jxwepn.png",
    title: "Sparking Issue",
    description:
      "Safe repair for microwave sparking problems to prevent hazards.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Microwave Oven",
  },
  {
    img: TECH_IMG_BASE + "oven-ser-img4_g2cdsy.png",
    title: "Electrical Connection Issue",
    description:
      "Reliable solution for microwave electrical connection faults.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Microwave Oven",
  },
  {
    img: TECH_IMG_BASE + "quickCheckTechImg_c1syfy.png",
    title: "QuickCheck",
    description:
      "Fast inspection & instant solution for your appliances or electrical issues.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    type: "Microwave Oven",
  },
  {
    img: TECH_IMG_BASE + "tv-ser-img1_ycz3kg.png",
    title: "New TV Installation",
    description: "Professional TV setup for a perfect viewing experience.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "Television",
    isPopular: true,
  },
  {
    img: TECH_IMG_BASE + "tv-ser-img2_qmjqol.png",
    title: "TV Uninstallation",
    description: "Safe and hassle-free TV removal service.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
  {
    img: TECH_IMG_BASE + "tv-ser-img3_wvawoh.png",
    title: "Display Problem",
    description: "Quick repair for blurry, flickering, or faulty TV display.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
  {
    img: TECH_IMG_BASE + "tv-ser-img4_j3xxfa.png",
    title: "Smart TV Remote Not Working",
    description: "Expert fix for unresponsive smart TV remotes.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
  {
    img: TECH_IMG_BASE + "tv-ser-img5_iutszb.png",
    title: "Lines on Screen",
    description:
      "Efficient solution to remove lines or distortions from your screen.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "Television",
    isPopular: true,
  },
  {
    img: TECH_IMG_BASE + "tv-ser-img6_enotpw.png",
    title: "Speaker or Sound Problem",
    description: "Clear and reliable sound repair for TV speakers",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
  {
    img: TECH_IMG_BASE + "tv-ser-img7_d5gdso.png",
    title: "LED TV Backlight Changing",
    description: "Fast backlight replacement for bright and even TV display.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
  {
    img: TECH_IMG_BASE + "tv-ser-img8_ycqakz.png",
    title: "Parts Replacement",
    description: "Genuine parts replacement to restore your TV’s performance.",
    rating: 4.5,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
  {
    img: TECH_IMG_BASE + "tv-ser-img9_nflvik.png",
    title: "TV Software Update",
    description: "Smart software updates to keep your TV running smoothly.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
  {
    img: TECH_IMG_BASE + "tv-ser-img10_zjhfm6.png",
    title: "Connectivity Issue (WiFi/HDMI/USB)",
    description: "Reliable fix for WiFi, HDMI, or USB connectivity problems.",
    rating: 4,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
  {
    img: TECH_IMG_BASE + "quickCheckTechImg_c1syfy.png",
    title: "QuickCheck",
    description:
      "Fast inspection & instant solution for your appliances or electrical issues.",
    rating: 5,
    duration: "30 mins",
    price: "120",
    type: "Television",
  },
];
